from __future__ import annotations

import pytest

from phase3.presentation.config import PresentationConfig
from phase3.presentation.schema import ChartType, SectionType
from phase3.presentation.templates import (
    BusinessTemplate,
    ExecutiveTemplate,
    FounderTemplate,
    InvestorTemplate,
    MarketTemplate,
    TechnologyTemplate,
    available_templates,
    create_template,
    get_template_class,
)
from phase3.presentation.templates.base import BaseTemplate


@pytest.fixture
def config() -> PresentationConfig:
    return PresentationConfig()


class TestBaseTemplate:
    def test_cannot_instantiate_abc(self) -> None:
        with pytest.raises(TypeError):
            BaseTemplate()

    def test_default_methods(self) -> None:
        class MinimalTemplate(BaseTemplate):
            @property
            def name(self) -> str:
                return "minimal"

            @property
            def description(self) -> str:
                return "Minimal"

            @property
            def report_type(self) -> str:
                return "minimal"

        t = MinimalTemplate()
        assert t.sections() == []
        assert t.chart_types() == []
        assert t.title({}) == "Minimal Report"
        assert t.subtitle({}) == "Generated by IdeaFormator Pipeline"

        t.configure(config)
        assert t._config is config


class TestBusinessTemplate:
    def test_name(self) -> None:
        assert BusinessTemplate().name == "business"

    def test_description(self) -> None:
        assert BusinessTemplate().description == "Business"

    def test_sections(self) -> None:
        sections = BusinessTemplate().sections()
        types = [s.section_type for s in sections]
        assert SectionType.executive_summary in types
        assert SectionType.top_findings in types
        assert SectionType.recommendations in types
        assert SectionType.appendix in types
        assert len(sections) == 4

    def test_sections_are_ordered(self) -> None:
        sections = BusinessTemplate().sections()
        for i in range(len(sections) - 1):
            assert sections[i].order <= sections[i + 1].order

    def test_chart_types(self) -> None:
        charts = BusinessTemplate().chart_types()
        assert ChartType.bar in charts
        assert ChartType.pie in charts

    def test_title(self) -> None:
        t = BusinessTemplate()
        assert t.title({"title": "Custom"}) == "Custom"
        assert t.title({}) == "Business Report"


class TestExecutiveTemplate:
    def test_name(self) -> None:
        assert ExecutiveTemplate().name == "executive"

    def test_description(self) -> None:
        assert ExecutiveTemplate().description == "Executive Summary"

    def test_report_type(self) -> None:
        assert ExecutiveTemplate().report_type == "executive_summary"

    def test_sections(self) -> None:
        sections = ExecutiveTemplate().sections()
        types = [s.section_type for s in sections]
        assert SectionType.executive_summary in types
        assert SectionType.top_findings in types
        assert SectionType.trend_analysis in types
        assert SectionType.opportunity_analysis in types
        assert SectionType.confidence in types
        assert SectionType.recommendations in types
        assert SectionType.appendix in types
        assert len(sections) == 7

    def test_chart_types(self) -> None:
        charts = ExecutiveTemplate().chart_types()
        assert ChartType.bar in charts
        assert ChartType.pie in charts
        assert ChartType.line in charts
        assert len(charts) == 3

    def test_title(self) -> None:
        t = ExecutiveTemplate()
        assert t.title({}) == "Executive Summary Report"


class TestInvestorTemplate:
    def test_name(self) -> None:
        assert InvestorTemplate().name == "investor"

    def test_description(self) -> None:
        assert InvestorTemplate().description == "Investor"

    def test_report_type(self) -> None:
        assert InvestorTemplate().report_type == "investor"

    def test_sections(self) -> None:
        sections = InvestorTemplate().sections()
        types = [s.section_type for s in sections]
        assert SectionType.opportunity_analysis in types
        assert SectionType.trend_analysis in types
        assert SectionType.confidence in types
        assert len(sections) == 7

    def test_chart_types(self) -> None:
        charts = InvestorTemplate().chart_types()
        assert ChartType.bar in charts
        assert ChartType.pie in charts
        assert ChartType.treemap in charts

    def test_title(self) -> None:
        t = InvestorTemplate()
        assert t.title({}) == "Investor Report"


class TestFounderTemplate:
    def test_name(self) -> None:
        assert FounderTemplate().name == "founder"

    def test_description(self) -> None:
        assert FounderTemplate().description == "Startup Opportunity"

    def test_report_type(self) -> None:
        assert FounderTemplate().report_type == "startup_opportunity"

    def test_sections(self) -> None:
        sections = FounderTemplate().sections()
        types = [s.section_type for s in sections]
        assert SectionType.opportunity_analysis in types
        assert SectionType.root_causes in types
        assert SectionType.evidence in types
        assert SectionType.reasoning_summary in types
        assert len(sections) == 8

    def test_chart_types(self) -> None:
        charts = FounderTemplate().chart_types()
        assert ChartType.bar in charts
        assert ChartType.line in charts
        assert ChartType.pie in charts

    def test_title(self) -> None:
        t = FounderTemplate()
        assert t.title({}) == "Startup Opportunity Report"


class TestTechnologyTemplate:
    def test_name(self) -> None:
        assert TechnologyTemplate().name == "technology"

    def test_description(self) -> None:
        assert TechnologyTemplate().description == "Technology Landscape"

    def test_report_type(self) -> None:
        assert TechnologyTemplate().report_type == "technology_landscape"

    def test_sections(self) -> None:
        sections = TechnologyTemplate().sections()
        types = [s.section_type for s in sections]
        assert SectionType.trend_analysis in types
        assert SectionType.charts in types
        assert SectionType.appendix in types
        assert SectionType.recommendations in types
        assert len(sections) == 6

    def test_chart_types(self) -> None:
        charts = TechnologyTemplate().chart_types()
        assert ChartType.bar in charts
        assert ChartType.timeline in charts
        assert ChartType.heatmap in charts

    def test_title(self) -> None:
        t = TechnologyTemplate()
        assert t.title({}) == "Technology Landscape Report"


class TestMarketTemplate:
    def test_name(self) -> None:
        assert MarketTemplate().name == "market"

    def test_description(self) -> None:
        assert MarketTemplate().description == "Market Intelligence"

    def test_report_type(self) -> None:
        assert MarketTemplate().report_type == "market_intelligence"

    def test_sections(self) -> None:
        sections = MarketTemplate().sections()
        types = [s.section_type for s in sections]
        assert SectionType.trend_analysis in types
        assert SectionType.opportunity_analysis in types
        assert SectionType.charts in types
        assert len(sections) == 7

    def test_chart_types(self) -> None:
        charts = MarketTemplate().chart_types()
        assert ChartType.bar in charts
        assert ChartType.line in charts
        assert ChartType.heatmap in charts
        assert ChartType.treemap in charts

    def test_title(self) -> None:
        t = MarketTemplate()
        assert t.title({}) == "Market Intelligence Report"


class TestTemplateInheritance:
    def test_executive_inherits_business_sections(self) -> None:
        executive = ExecutiveTemplate()
        business = BusinessTemplate()
        exec_types = {s.section_type for s in executive.sections()}
        bus_types = {s.section_type for s in business.sections()}
        assert bus_types.issubset(exec_types)

    def test_investor_inherits_business_sections(self) -> None:
        investor = InvestorTemplate()
        business = BusinessTemplate()
        inv_types = {s.section_type for s in investor.sections()}
        bus_types = {s.section_type for s in business.sections()}
        assert bus_types.issubset(inv_types)

    def test_founder_inherits_business_sections(self) -> None:
        founder = FounderTemplate()
        business = BusinessTemplate()
        fnd_types = {s.section_type for s in founder.sections()}
        bus_types = {s.section_type for s in business.sections()}
        assert bus_types.issubset(fnd_types)

    def test_market_inherits_business_sections(self) -> None:
        market = MarketTemplate()
        business = BusinessTemplate()
        mkt_types = {s.section_type for s in market.sections()}
        bus_types = {s.section_type for s in business.sections()}
        assert bus_types.issubset(mkt_types)

    def test_technology_not_inheriting_business(self) -> None:
        assert not isinstance(TechnologyTemplate(), BusinessTemplate)
        assert not issubclass(TechnologyTemplate, BusinessTemplate)

    def test_configure_all_templates(self, config: PresentationConfig) -> None:
        for name in available_templates():
            t = create_template(name)
            t.configure(config)
            assert t._config is config


class TestTemplateRegistry:
    def test_available_templates(self) -> None:
        available = available_templates()
        assert "executive" in available
        assert "investor" in available
        assert "founder" in available
        assert "technology" in available
        assert "market" in available
        assert "business" in available
        assert len(available) == 6

    def test_get_template_class(self) -> None:
        cls = get_template_class("executive")
        assert cls is ExecutiveTemplate

    def test_get_template_class_unknown(self) -> None:
        with pytest.raises(KeyError, match="Unknown template"):
            get_template_class("unknown")

    def test_create_template(self) -> None:
        t = create_template("executive")
        assert isinstance(t, ExecutiveTemplate)
        assert t.name == "executive"

    def test_create_template_unknown(self) -> None:
        with pytest.raises(KeyError):
            create_template("unknown")

    def test_all_templates_creatable(self) -> None:
        for name in available_templates():
            t = create_template(name)
            assert t.name == name
            assert isinstance(t, BaseTemplate)

    def test_all_templates_have_sections(self) -> None:
        for name in available_templates():
            t = create_template(name)
            assert len(t.sections()) > 0

    def test_all_templates_have_chart_types(self) -> None:
        for name in available_templates():
            t = create_template(name)
            assert len(t.chart_types()) > 0

    def test_all_templates_have_title(self) -> None:
        for name in available_templates():
            t = create_template(name)
            title = t.title({})
            assert isinstance(title, str)
            assert len(title) > 0

    def test_all_templates_have_subtitle(self) -> None:
        for name in available_templates():
            t = create_template(name)
            subtitle = t.subtitle({})
            assert isinstance(subtitle, str)
            assert len(subtitle) > 0


class TestSectionsOrdering:
    def test_all_templates_sections_ordered(self) -> None:
        for name in available_templates():
            t = create_template(name)
            sections = t.sections()
            for i in range(len(sections) - 1):
                assert sections[i].order <= sections[i + 1].order, (
                    f"Template '{name}' sections not ordered: "
                    f"{sections[i].title}({sections[i].order}) > "
                    f"{sections[i+1].title}({sections[i+1].order})"
                )

    def test_no_duplicate_orders(self) -> None:
        for name in available_templates():
            t = create_template(name)
            orders = [s.order for s in t.sections()]
            assert len(orders) == len(set(orders)), (
                f"Template '{name}' has duplicate section orders: {orders}"
            )

    def test_no_duplicate_section_types(self) -> None:
        for name in available_templates():
            t = create_template(name)
            types = [s.section_type for s in t.sections()]
            assert len(types) == len(set(types)), (
                f"Template '{name}' has duplicate section types: {types}"
            )
