from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from phase3.presentation.config import PresentationConfig
from phase3.presentation.schema import ChartType, SectionDefinition


class BaseTemplate(ABC):
    _config: PresentationConfig | None = None

    @property
    @abstractmethod
    def name(self) -> str:
        ...

    @property
    @abstractmethod
    def description(self) -> str:
        ...

    @property
    @abstractmethod
    def report_type(self) -> str:
        ...

    def sections(self) -> list[SectionDefinition]:
        return []

    def chart_types(self) -> list[ChartType]:
        return []

    def configure(self, config: PresentationConfig) -> None:
        self._config = config

    def title(self, data: dict[str, Any]) -> str:
        return f"{self.description} Report"

    def subtitle(self, data: dict[str, Any]) -> str:
        return "Generated by IdeaFormator Pipeline"
